export const notizenText = [
  "Hier ist Platz für Deine ganz persönlichen Notizen. Was hast Du in Deinem Prozess zu weniger Schmerz und körperlchem Leid festgestellt? Was ist Dir wichtig und willst es hier für Dich festhalten, um später darauf zurückzugreifen?",
];
export const stressAbschreibenText = [
  "In der letzten Übung hast Du eine Liste erstellt, mit Dingen, die in Dir Stress erzeugen. Das ist ein guter erster Schritt, um sich diesen Stressoren bewusst zu werden. Nun wollen wir aber noch ein wenig tiefer eintauchen und die einzelnen Stressfaktoren näher betrachten. Vielleicht sind Dir auch schon zuvor einige Gedanken zu den einzelnen Punkten aufgekommen.",
  "Versuche jetzt 12 Minuten lang in einen kreativen Schreibprozess zu kommen, bei dem Du einfach frei zu einem Thema aus der Sammlung Gedanken aufschreibst. Du musst keinen Literaturnobelpreis anstreben, sondern die Dinge, die Dir in den Sinn kommen ins Handy oder aufs Papier zu bringen. Wähle selbst Dein Medium. Manchen Menschen fällt es leichter, mit Stift und Papier zu arbeiten. Nach einer Weile solltest Du in Deinen Körper spüren. Was fühlst Du dort und wo? Sorgt ein Streit von letzter Woche noch immer für angespannte Nackenmuskeln oder Bauchgrummeln? Gehe diesen Empfindungen nach und schreibe auch darüber. Werte dabei nicht, sondern nimm einfach war und benenne. Damit zeigst Du Deinem Unterbewusstsein, dass es okay ist, auch unangenehme Gefühle zu spüren.",
  'Nach Ablauf der Zeit ertönt der Wecker. Klicke nun auf "Zerstören" bzw. zerreiß Dein Blatt oder vernichte es anders. Damit nimmst Du symbolisch Abschied von dem belastenden Themen. Wiederhole diese Übung so oft, wie Du magst und finde eine gute Routine für Dich - vielleicht immer abends nach dem Essen. Streiche so Stück für Stück die Themen aus der vorherigen Übung und merke, wie vielleicht ein wenig Entspanntheit sich einstellt.',
];
export const stressSammelnText = [
  "Wie Du nun schon weißt, können sich Stress und damit negative unterdrückte Gefühle mit der Zeit aufbauen und dann zu unangenehmen TMS-Symptomen führen. Lasst uns nun also ergründen, wie wir den Druck auf unser System ein wenig ablassen können. Dazu sollten wir uns zu allererst einmal bewusst machen, was in unserem Leben aktuell Stress verursacht.",
  "Häufig sind wir im Alltag so beschäftigt, dass wir nur selten innehalten, um darüber nachzudenken. Hier hast Du nun die Gelegenheit, Dinge aufzuschreiben, von denen Du denkst, dass sie für Dich Stress verursachen. Das können schwierige familiäre Situationen, Ärger auf Arbeit, aber auch freudige Entwicklungen wie eine Befürderung oder eine bevorstehende Hochzeit sein. Stressoren können in der Vergangenheit liegen, ganz aktuell sein oder auch Zukunftsängste betreffen.",
  'Wie detailiert Du vorgehst entscheidest Du selbst. Wichtig ist, dass Du mit den Schlagwörtern etwas anfangen kannst. Diese Liste ist ganz für Dich, zögere also nicht ganz offen mit Dir zu sein. Es handelt sich außerdem um eine offene Liste. Wann immer Dir neue Themen einfallen, schreibe sie dazu. Nachdem Du die nächste Übung "Stess abschreiben" begonnen hast, kannst Du hier zurückkommen und bearbeitete Themen aus der Liste streichen.',
];
export const positiveBotschaftenText = [
  "In dieser ersten Übung geht es darum, für Entspannung in unserem Unterbewusstsein zu sorgen. Im Kurs hast Du gelernt, wie selbstkritische und verzweifelnde Gedanken den Teufelskreis aus Furcht und Schmerz antreiben und befeuern. Ein Weg daraus auszubrechen, ist es, bewusst positive Botschaften an uns zu senden. Vielleicht fällt es Dir schwer, dies zu Beginn mit Überzeugung zu tun. Versuch macht klug. Probier es aus und schau, wie es sich für Dich anfühlt. ",
  " Als kleine Inspiration habe ich in dieser Übung drei sehr kraftvolle Botschaften vorbereitet, die an den Wurzeln vieler ungesunder Einstellungen zu uns selbst ansetzen.",
  '"Ich bin gesund." - Besonders, wenn sich chronische Schmerzen und TMS-Symptome schon über Jahre erstrecken und in dieser Zeit in Dir viel Leid erzeugt haben, fällt es Dir sicher schwer, diesen Satz anzunehmen. Dr. Sarno wies oft daraufhin, dass TMS-Patienten geheilt seien. Sie müssten es nur selbst glauben und darum geht es hier. So lange Du Deinem Unterbewusstsein klar machst, dass Du Dir weiter große Sorgen, um bestimmte Symptome machst, weiß es, dass diese Symptome ihren Zweck erfüllen.',
  '"Ich bin sicher." - Die allermeisten Herausforderungen, Probleme und Traumata liegen in der Vergangenheit oder bestehen in angstvollen Zukunftsvisionen. Hier und in diesem Moment bist Du sicher. Lasse es Dich wissen!',
  '"Ich bin entspannt." - Im hektischen Alltag laufen wir im Automatikmodus und der ist häufig aus eigener Gewohnheit aufgedreht, leistungsmaximiert und von Reizüberflutung geprägt. Stress wird sehr individuell wahrgenommen und kann von Dir auch gemacht werden. Genauso kannst Du aber auch einen Zustand von Gelassenheit kultivieren.',
  "Diese drei Botschaften sind Vorschläge, die für viele Menschen gut funktionieren. Vielleicht möchtest Du aber auch selbst eigene positive Botschaften ergänzen? Wiederhole die positiven Botschaften regelmäßig nach eigener Vorliebe, leise oder laut und versuche auch daran zu denken, wenn Du vielleicht das nächste Mal stark unter Schmerzen leidest, nach einem unangenehmen Streit oder wenn Du von einem Termin zum nächsten rennst. Was machen diese positiven Botschaften mit Dir?",
];
export const wasTutMirGutText = [
  "In vergangenen Übungen hast Du Dich schon ein wenig mit Dir beschäftigt. Du hast Dich Dingen gewidmet, die Stress in Dir erzeugen und Botschaften, die Dich beruhigen können und Zuversicht schenken.",
  'Da möchte ich ansetzen. Ein wichtiges Puzzleteil zu Deinem Wohlbefinden liegt in Deinen alltäglichen Handlungen. Sie ergeben sich teils aus simplen Notwendigkeiten, wie den Herausforderungen eines Jobs, um Geld zu verdienen oder Erledigungen für die Familie bis hin zum Ablesen des Stromzählers. Du hast hier aber zum einen die Möglichkeit, zu entscheiden, wie Du diese Dinge angehst (dazu später mehr) aber verfügst auch über Freizeite, die Du für Dich individuell gestalten kannst. Wann hast Du Dir das letzte Mal die Frage gestellt: "Was würde mir jetzt richtig gut tun?"',
  "Häufig handeln wir in einem Automatikmodus in eng eingefahrenen Gewohnheiten. Brich doch einmal ganz bewusst aus. Stell Dir nun hier diese Frage und notiere einige dieser Dinge. Vielleicht kannst Du davon ja auch einiges umsetzen in den nächsten Tagen und schauen, wie es Dir damit geht?",
  "Ich habe Dir hier schon mal drei Denkanstöße aufgeschrieben. Das tut mir gut: ein warmes Bad im Kerzenschein, ein gutes Buch vorm Einschlafen und Spazierengehen im Wald.",
];

export const wasTutMirNichtGutText = [
  "Nachdem Du einige Dinge notiert hast, die Dir helfen, zu entspannen, dem Alltag zu entkommen, bitte ich Dich nun auch die vielleicht unangenehmen Aktivitäten zu notieren, die oft das Gegenteil bewirken.",
  "Wovon wächst die Anspannung in Dir? Ist es schwer für Dich Ruhe zu ertragen, was löst dieses Unbehagen aus? Möchtest Du damit vielleicht unterbewusst Deine Gedanken und Gefühle verdrängen?",
  "Spüre in Dich hinein. Denke an Handlungen und Gewohnehiten, denen Du oft nachgehst. Wie geht es Dir während und vor allem, wie geht es Dir auch danach.",
  "Alkohol ist ein gutes Beispiel für eine ungesunde Stressbewältigungsstrategie. Im Moment des Rausches ist Deine Empfindung temporär gedämpft und Du verspürst mitunter eine leichte Entspannung. Nach dem Rausch aber folgt der Kater und die Einsicht, dass es Dir noch nicht besser geht.",
  "Welche Gewohnheiten kannst Du in Deinem Leben ausmachen, die für Dir auf lange Sicht nicht gut tun? Exzessives und ungesundes Essen, hoher Medienkonsum, ein hektischer Alltag ohne Pausen?",
  "Notiere es hier zu den Vorschlägen, überlege wie Du es schaffen kannst, weniger dieser Gewohnheiten und mehr entspannende Gewohnheiten nachzugehen. Was kannst Du ganz persönlich dafür tun?",
];

//inspiriert durch YouTube Video: https://www.youtube.com/watch?v=bu08QqfsS3o
//kostenlose transcripts mit: https://tactiq.io/tools/youtube-transcript
export const painReprocessingEntwurf = [
  "Lass uns eintauchen, um mit diesem Gehirntraining zu beginnen. Wir kombinieren tiefes Atmen mit Botschaften der Sicherheit. Begebe Dich dazu in eine bequeme Position. Du kannst auf einem Stuhl sitzen, stehen oder liegen und einen Platz finden, der für Dich bequem ist. Nimm eine Position ein, die sich für Dich sicher anfühlt. Wir starten mit einer kleinen Atemübung. Um Dein System zu beruhigen und Dein Unterbewusstsein zu regulieren. Dann werden wir üben, diese Botschaften von Sicherheit zu geben. Wenn Sie möchten, kannst Du Deine Augen schließen oder Deinen Blick senken. Atme nun tief druch die Nase in den Bauch ein. Wenn Sie einatmen, fülle zuerst deinen unteren Unterleib, dann den Oberleib und zuletzt den Brustkorb, so dass alles mit Luft gefüllt ist. Spüre, wie sich alles dehnt und atme dann wieder langsam durch die Nase aus. Zuerst aus der Brust, dann aus dem Oberbauch und dann dem Unterbauch. Atme so ein paar Mal. Unterbauch, Oberbauch, Brustkorb ein und dann Brustkorb, Oberbauch und Unterbauch aus. Während du das übst, schau, dass Dein Ausatmen etwa doppelt so lang wie Dein Einatmen wird. Konzentriere Dich sich auf die Empfindungen in Deinem Körper.",
];

//hier nächste Texte einfügen und dann in Dateien einbauen mit ctrl+j können linebreaks entfernt werden mit ',' Zeilenumbrüche eingefügt
export const nextText = "";
